// export const USER_LOGIN = 'USER_LOGIN';
export const constants= {
    USER_PHONE_CODE_REQUEST: 'USER_PHONE_CODE_REQUEST',
    USER_PHONE_CODE_SUCCESS: 'USER_PHONE_CODE_SUCCESS',
    USER_PHONE_CODE_FAILURE: 'USER_PHONE_CODE_FAILURE',

    USER_OTP_SUCCESS: 'USER_OTP_SUCCESS',
    USER_OTP_FAILURE: 'USER_OTP_FAILURE',
    USER_OTP_REQUEST: 'USER_OTP_REQUEST',

    USER_SIGNUP_REQUEST: 'USER_SIGNUP_REQUEST',
    USER_SIGNUP_SUCCESS: 'USER_SIGNUP_SUCCESS',
    USER_SIGNUP_FAILURE: 'USER_SIGNUP_FAILURE',

    USER_OTP_VERIFY_REQUEST: 'USER_OTP_VERIFY_REQUEST',
    USER_OTP_VERIFY_SUCCESS: 'USER_OTP_VERIFY_SUCCESS',
    USER_OTP_VERIFY_FAILURE: 'USER_OTP_VERIFY_FAILURE',

    USER_LOGIN_REQUEST: 'USER_LOGIN',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAILURE: 'USER_LOGIN_FAILURE',

    DASHBOARD_DATA_REQUEST: 'DASHBOARD_DATA_REQUEST',
    DASHBOARD_DATA_SUCCESS: 'DASHBOARD_DATA_SUCCESS',
    DASHBOARD_DATA_FAILURE: 'DASHBOARD_DATA_FAILURE',

    CREATE_LOAN_OFFER_REQUEST: 'CREATE_LOAN_OFFER_REQUEST',
    CREATE_LOAN_OFFER_SUCCESS: 'CREATE_LOAN_OFFER_SUCCESS',
    CREATE_LOAN_OFFER_FAILURE: 'CREATE_LOAN_OFFER_FAILURE',
}